"""Profile the raw CSVs BEFORE modelling them.

The point of running this first is to catch the things that would otherwise
be discovered as a wrong number three models downstream: keys that are not
unique, columns that are mostly null, a category vocabulary that does not
match its translation table.

Everything here reads the CSVs directly, not the warehouse, so it can be run
on a fresh checkout before dbt has ever executed.

Output: docs/data_profile.md
"""

from __future__ import annotations

import duckdb
import pandas as pd

from . import DOCS_DIR, RAW_DIR

TABLES = [
    "olist_orders_dataset",
    "olist_order_items_dataset",
    "olist_order_payments_dataset",
    "olist_order_reviews_dataset",
    "olist_customers_dataset",
    "olist_sellers_dataset",
    "olist_products_dataset",
    "olist_geolocation_dataset",
    "product_category_name_translation",
]

# Columns each table is *claimed* to be unique on, so the claim gets checked
# rather than assumed. Several of these are expected to FAIL -- that is the
# finding, and the models are built around it.
CLAIMED_KEYS = {
    "olist_orders_dataset": ["order_id", "customer_id"],
    "olist_customers_dataset": ["customer_id", "customer_unique_id"],
    "olist_sellers_dataset": ["seller_id"],
    "olist_products_dataset": ["product_id"],
    "olist_order_reviews_dataset": ["review_id", "order_id"],
    "product_category_name_translation": ["product_category_name"],
    "olist_geolocation_dataset": ["geolocation_zip_code_prefix"],
}


def _rel(table: str) -> str:
    return (f"read_csv_auto('{RAW_DIR / (table + '.csv')}', "
            f"all_varchar=true, header=true)")


def profile_table(con, table: str) -> tuple[pd.DataFrame, int]:
    n = con.execute(f"select count(*) from {_rel(table)}").fetchone()[0]
    cols = con.execute(f"select * from {_rel(table)} limit 0").df().columns.tolist()

    rows = []
    for col in cols:
        stats = con.execute(f"""
            select count({col}) as non_null,
                   count(distinct {col}) as n_distinct,
                   min(length({col})) as min_len,
                   max(length({col})) as max_len
            from {_rel(table)}
        """).fetchone()
        sample = con.execute(
            f"select {col} from {_rel(table)} where {col} is not null limit 1"
        ).fetchone()
        rows.append({
            "column": col,
            "non_null": stats[0],
            "null_pct": 100.0 * (n - stats[0]) / n if n else 0.0,
            "distinct": stats[1],
            "min_len": stats[2],
            "max_len": stats[3],
            "example": (str(sample[0])[:32] if sample else ""),
        })
    return pd.DataFrame(rows), n


def check_keys(con) -> pd.DataFrame:
    rows = []
    for table, keys in CLAIMED_KEYS.items():
        n = con.execute(f"select count(*) from {_rel(table)}").fetchone()[0]
        for key in keys:
            d = con.execute(
                f"select count(distinct {key}) from {_rel(table)}"
            ).fetchone()[0]
            rows.append({
                "table": table,
                "column": key,
                "rows": n,
                "distinct": d,
                "is_unique": d == n,
                "duplicated_rows": n - d,
            })
    return pd.DataFrame(rows)


def main() -> int:
    con = duckdb.connect()

    key_report = check_keys(con)

    cat_gap = con.execute(f"""
        select count(*) from (
            select distinct product_category_name
            from {_rel('olist_products_dataset')}
            where product_category_name is not null
        ) p
        left join {_rel('product_category_name_translation')} t
               on p.product_category_name = t.product_category_name
        where t.product_category_name is null
    """).fetchone()[0]

    ts_range = con.execute(f"""
        select min(order_purchase_timestamp), max(order_purchase_timestamp)
        from {_rel('olist_orders_dataset')}
    """).fetchone()

    monthly = con.execute(f"""
        select strftime(cast(order_purchase_timestamp as timestamp), '%Y-%m') as month,
               count(*) as orders,
               round(100.0 * avg((order_delivered_customer_date is not null)::int), 1)
                   as pct_with_delivery
        from {_rel('olist_orders_dataset')}
        group by 1 order by 1
    """).df()

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    out = DOCS_DIR / "data_profile.md"

    parts = [
        "# Source data profile",
        "",
        "Generated by `olist/profile_source.py`, reading the CSVs directly. Run",
        "before any modelling so that the surprises below shape the models rather",
        "than being discovered downstream as a wrong number.",
        "",
        f"Purchase timestamps span **{ts_range[0]}** to **{ts_range[1]}**.",
        "",
        "## Key uniqueness: claimed vs actual",
        "",
        "Three of these fail, and each failure changes a model:",
        "",
        "- `olist_order_reviews_dataset.review_id` and `.order_id` are both",
        "  non-unique. Resolved in `stg_order_reviews`.",
        "- `olist_customers_dataset.customer_unique_id` is non-unique **by design**:",
        "  that is the person key, and its duplicates ARE the repeat customers. The",
        "  unique-per-row `customer_id` is the per-order key. Getting these the wrong",
        "  way round makes the repeat rate exactly zero.",
        "- `olist_geolocation_dataset.geolocation_zip_code_prefix` has ~53 rows per",
        "  prefix. It is a point cloud, not a lookup; `int_zip_centroids` reduces it.",
        "",
        key_report.to_markdown(index=False),
        "",
        "## Category translation coverage",
        "",
        f"{cat_gap} product categories have no English translation. They are given",
        "hand-written names in `stg_products` rather than dropped, because a null",
        "category silently disappears from every category-level group-by.",
        "",
        "## Monthly volume and delivery completeness",
        "",
        "The two tails are why the analysis window is 2017-01-01 to 2018-08-31:",
        "2016 is a sparse pilot, and the final months are right-censored — orders",
        "exist but no delivery had been recorded when the snapshot was cut.",
        "",
        monthly.to_markdown(index=False),
        "",
        "## Column-level profile",
        "",
    ]

    for table in TABLES:
        prof, n = profile_table(con, table)
        parts += [f"### `{table}` — {n:,} rows", "",
                  prof.to_markdown(index=False, floatfmt=",.2f"), ""]

    con.close()
    out.write_text("\n".join(parts) + "\n")
    print(f"wrote {out}")

    failed = key_report[~key_report["is_unique"]]
    print(f"\n{len(failed)} of {len(key_report)} claimed keys are NOT unique:")
    for _, r in failed.iterrows():
        print(f"  {r['table']}.{r['column']}: "
              f"{r['rows']:,} rows, {r['distinct']:,} distinct")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
